[project]
name = "leetcode-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "coverage>=7.7.1",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
]
[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true
